title: "The $WRATH Token"
description: "The official website and repository for the $WRATH ERC-20 Token."

twitter_username: "TokenWrath"
github_username:  "TokenWRATH"

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
